# Generated by Django 5.1.4 on 2024-12-08 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_booktransaction_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktransaction',
            name='borrow_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='expected_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
